In [5]:
import os

In [6]:
from keras.preprocessing import image

In [7]:
import cv2

In [8]:
categories = ['with_mask','without_mask']

In [9]:
data=[]
for category in categories:
    path=os.path.join('train',category)
    label=categories.index(category)  #used for indexing, 0 for with mask and 1 for without mask
    
    for file in os.listdir(path):
        
        img_path = os.path.join(path,file)
        img = cv2.imread(img_path)
        img = cv2.resize(img,(224,224))
        
        data.append([img,label])

In [10]:
len(data)

1507

In [48]:
data

[[array([[[108, 109, 123],
          [ 99, 100, 113],
          [ 86,  86,  98],
          ...,
          [203, 190, 198],
          [200, 187, 195],
          [199, 186, 194]],
  
         [[109, 109, 124],
          [100, 101, 114],
          [ 87,  87,  99],
          ...,
          [202, 188, 196],
          [199, 186, 194],
          [197, 184, 192]],
  
         [[110, 111, 124],
          [101, 102, 115],
          [ 88,  88, 100],
          ...,
          [199, 186, 194],
          [196, 183, 192],
          [194, 181, 190]],
  
         ...,
  
         [[248, 231, 244],
          [248, 231, 244],
          [248, 231, 244],
          ...,
          [ 84,  98, 147],
          [ 79,  93, 142],
          [ 76,  90, 139]],
  
         [[247, 230, 243],
          [247, 229, 243],
          [246, 229, 242],
          ...,
          [ 85,  99, 148],
          [ 80,  94, 143],
          [ 77,  91, 140]],
  
         [[246, 229, 242],
          [245, 229, 241],
          [245, 228, 241

In [11]:
import random

In [12]:
random.shuffle(data)            #used for shuffling the data as images are in the order with_mask -> without_mask

In [13]:
X=[]
y=[]

for features,label in data:
    X.append(features)
    y.append(label)

In [14]:
len(X)

1507

In [15]:
len(y)

1507

In [16]:
import numpy as np

In [17]:
X=np.array(X)
y=np.array(y)

In [18]:
X.shape                                  #1507 images of size (224,224,3)

(1507, 224, 224, 3)

In [19]:
y.shape

(1507,)

In [20]:
X

array([[[[108, 109, 123],
         [ 99, 100, 113],
         [ 86,  86,  98],
         ...,
         [203, 190, 198],
         [200, 187, 195],
         [199, 186, 194]],

        [[109, 109, 124],
         [100, 101, 114],
         [ 87,  87,  99],
         ...,
         [202, 188, 196],
         [199, 186, 194],
         [197, 184, 192]],

        [[110, 111, 124],
         [101, 102, 115],
         [ 88,  88, 100],
         ...,
         [199, 186, 194],
         [196, 183, 192],
         [194, 181, 190]],

        ...,

        [[248, 231, 244],
         [248, 231, 244],
         [248, 231, 244],
         ...,
         [ 84,  98, 147],
         [ 79,  93, 142],
         [ 76,  90, 139]],

        [[247, 230, 243],
         [247, 229, 243],
         [246, 229, 242],
         ...,
         [ 85,  99, 148],
         [ 80,  94, 143],
         [ 77,  91, 140]],

        [[246, 229, 242],
         [245, 229, 241],
         [245, 228, 241],
         ...,
         [ 86, 100, 149],
        

In [21]:
y

array([1, 0, 1, ..., 0, 1, 1])

In [22]:
X=X/255 #normalizing the data

In [23]:
#Normalization typically means rescales the values into a range of [0,1]. Standardization typically means rescales data to have a mean of 0 and a standard deviation of 1 (unit variance).

In [24]:
#standardiztion is method of scaling the data, i.e subtracting the mean and "dividing the difference by standard deviation"

In [25]:
X

array([[[[0.42352941, 0.42745098, 0.48235294],
         [0.38823529, 0.39215686, 0.44313725],
         [0.3372549 , 0.3372549 , 0.38431373],
         ...,
         [0.79607843, 0.74509804, 0.77647059],
         [0.78431373, 0.73333333, 0.76470588],
         [0.78039216, 0.72941176, 0.76078431]],

        [[0.42745098, 0.42745098, 0.48627451],
         [0.39215686, 0.39607843, 0.44705882],
         [0.34117647, 0.34117647, 0.38823529],
         ...,
         [0.79215686, 0.7372549 , 0.76862745],
         [0.78039216, 0.72941176, 0.76078431],
         [0.77254902, 0.72156863, 0.75294118]],

        [[0.43137255, 0.43529412, 0.48627451],
         [0.39607843, 0.4       , 0.45098039],
         [0.34509804, 0.34509804, 0.39215686],
         ...,
         [0.78039216, 0.72941176, 0.76078431],
         [0.76862745, 0.71764706, 0.75294118],
         [0.76078431, 0.70980392, 0.74509804]],

        ...,

        [[0.97254902, 0.90588235, 0.95686275],
         [0.97254902, 0.90588235, 0.95686275]

In [26]:
X[0]

array([[[0.42352941, 0.42745098, 0.48235294],
        [0.38823529, 0.39215686, 0.44313725],
        [0.3372549 , 0.3372549 , 0.38431373],
        ...,
        [0.79607843, 0.74509804, 0.77647059],
        [0.78431373, 0.73333333, 0.76470588],
        [0.78039216, 0.72941176, 0.76078431]],

       [[0.42745098, 0.42745098, 0.48627451],
        [0.39215686, 0.39607843, 0.44705882],
        [0.34117647, 0.34117647, 0.38823529],
        ...,
        [0.79215686, 0.7372549 , 0.76862745],
        [0.78039216, 0.72941176, 0.76078431],
        [0.77254902, 0.72156863, 0.75294118]],

       [[0.43137255, 0.43529412, 0.48627451],
        [0.39607843, 0.4       , 0.45098039],
        [0.34509804, 0.34509804, 0.39215686],
        ...,
        [0.78039216, 0.72941176, 0.76078431],
        [0.76862745, 0.71764706, 0.75294118],
        [0.76078431, 0.70980392, 0.74509804]],

       ...,

       [[0.97254902, 0.90588235, 0.95686275],
        [0.97254902, 0.90588235, 0.95686275],
        [0.97254902, 0

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [28]:
X_train.shape

(1205, 224, 224, 3)

In [29]:
X_test.shape

(302, 224, 224, 3)

In [30]:
from keras.applications.vgg16 import VGG16

In [31]:
vgg = VGG16()

In [32]:
import tensorflow as tf

In [33]:
print(tf.__version__)

2.3.0


In [34]:
vgg.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [35]:
from keras import Sequential

In [36]:
model= Sequential()

In [37]:
for layer in vgg.layers[:-1]:
    model.add(layer)

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       2

In [39]:
for layer in model.layers:
    layer.trainable = False

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       2

In [41]:
from keras.layers import Dense

In [42]:
model.add(Dense(1,activation='sigmoid'))

In [43]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       2

In [44]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])
#Adam optimization is a stochastic gradient descent method that is based on adaptive estimation of first-order and second-order moments
#It is a replacement optimization algorithm for stochastic gradient descent for training deep learning models

In [45]:
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
38/38 [==============================] - 407s 11s/step - loss: 0.5745 - accuracy: 0.7427 - val_loss: 0.3945 - val_accuracy: 0.8808
Epoch 2/5
38/38 [==============================] - 398s 10s/step - loss: 0.3416 - accuracy: 0.8788 - val_loss: 0.3067 - val_accuracy: 0.8907
Epoch 3/5
38/38 [==============================] - 402s 11s/step - loss: 0.2760 - accuracy: 0.9137 - val_loss: 0.2478 - val_accuracy: 0.9106
Epoch 4/5
38/38 [==============================] - 402s 11s/step - loss: 0.2367 - accuracy: 0.9286 - val_loss: 0.2143 - val_accuracy: 0.9305
Epoch 5/5
38/38 [==============================] - 404s 11s/step - loss: 0.2089 - accuracy: 0.9369 - val_loss: 0.1950 - val_accuracy: 0.9238


In [49]:
#We can divide the dataset of 2000 examples into batches of 500 then it will take 4 iterations to complete 1 epoch.

In [50]:
cap = cv2.VideoCapture(0)

In [65]:
while True:
    ret, frame = cap.read()
    cv2.imshow("window",frame)
    
    #calling the detection method
    img = cv2.resize(frame,(224,224))
    y_pred = detect_facemask(img)
    
    if y_pred == 0:
        draw_label(frame,"Mask",(30,30),(0,255,0))
    else:
        draw_label(frame,"No Mask",(30,30),(0,0,255))
    
    cv2.imshow("window",frame)
    
    if cv2.waitKey(1) & 0xFF == ord('x'):
        break
        
cv2.destroyAllWindows()

In [60]:
def detect_facemask(img):
    y_pred = (model.predict(img.reshape(1,224,224,3))>0.5).astype(np.int32)
    return y_pred[0][0]

In [66]:
img1 = cv2.imread("sample/sample1.jpg")
img1 = cv2.resize(img1,(224,224))

In [62]:
detect_facemask(img1)

0

In [63]:
def draw_label(img,text,pos,bg_color):
    text_size = cv2.getTextSize(text,cv2.FONT_HERSHEY_SIMPLEX,1,cv2.FILLED)
    end_x = pos[0] + text_size[0][0] + 2
    end_y = pos[1] + text_size[0][1] - 2
    
    cv2.rectangle(img,pos,(end_x,end_y),bg_color,cv2.FILLED)
    cv2.putText(img,text,pos,cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),1,cv2.LINE_AA)